### ISSUE TITLE
Unhandled Exception in RenderForm.GetBackground()

### ISSUE THREAD

**Issue by DavidRawling** [Ventajou/WPInfo#8]
Running from a scheduled task. Exception "Parameter is not valid" .

Loading with command "WPInfo /LoadFile=User.wpi /Silent". References the User folder (relative) containing a single image.

*************\* Exception Text **************
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at Ventajou.WPInfo.RenderForm.GetBackground()
   at Ventajou.WPInfo.RenderForm.FormLoaded(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by DavidRawling** [comment]
Does not seem to happen if the resolution is specified on the command line (but even then it did not correctly process - the resulting image is not the resolution specified)
